server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profile:
    active: native
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: venda
      auto-index-creation: true

application-version: 1.0